### ISSUE TITLE
Update interval day selection

### ISSUE THREAD

**Issue by hakunti** [ruuvi/ruuvi.gwui.html#104]
Use simple tick boxes to select a day when update would done. Now it's too complex and hard to understand.
![image](https://user-images.githubusercontent.com/25771106/131213870-697f0e93-5004-4f19-b852-08018bf0325e.png)

**Comment by TheSomeMan** [comment]
![image](https://user-images.githubusercontent.com/4346875/131249409-37d06277-23b4-439f-af80-cc6d03dc68a9.png)
is that ok?

**Comment by laurijamsa** [comment]
Yes, looks good.
