### ISSUE TITLE
On macOS hotspot configuration window, page is scrolled automatically

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gwui.html#105]
When the hotspot configuration page opens, it is automatically scrolled down a bit. Not completely to the end of the page, but ~halfway. This same issue is with all the pages when user is clicking NEXT on the configuration wizard.

![image](https://user-images.githubusercontent.com/1311912/131238553-6d736b0f-8a72-49a0-803d-fc16617fe03a.png)

**Comment by markoaamunkajo** [comment]
Looks like not MacOS only, same on Android Chrome

![Screenshot_20210829-150237_Chrome](https://user-images.githubusercontent.com/50437378/131243364-055f6efd-2ce7-4e3f-8dfe-290c53f4808e.jpg)

**Comment by aj-ua** [comment]
Uploaded fix to https://github.com/ruuvi/ruuvi.gwui.html/pull/115
Please test on real device.
