### ISSUE TITLE
Login from network page doesn't look good

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gwui.html#106]
![image](https://user-images.githubusercontent.com/1311912/131238951-18a68149-eda9-487d-a121-2c476b47738f.png)

**Comment by TheSomeMan** [comment]
@laurijamsa is this screenshot from 1.8.0 ?
I improved it a little in v1.8.1, now it looks like this:
![image](https://user-images.githubusercontent.com/4346875/131295061-c22bd181-6803-45f4-a844-bb0c031b6aa9.png)

**Comment by TheSomeMan** [comment]
Fixed in commit https://github.com/ruuvi/ruuvi.gwui.html/pull/110/commits/1bdad8e92f938fc848b5fb4e51211345fe215e41

**Comment by aj-ua** [comment]
I made some style improvements for Auth page. Created PR.
