### ISSUE TITLE
Move the authentication setting page to the basic flow

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gwui.html#107]
Currently it can be found only by following the advanced path on the configuration wizard. Let's consider moving position of this page so that it could be found easier.

**Comment by ojousima** [comment]
It's been considered, and has to be done for https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/315. Editing title to reflect the decision

**Comment by markoaamunkajo** [comment]
Moving to done
