### ISSUE TITLE
Auto update isn't supporting manual URLs

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gwui.html#109]
When I try to configure Gateway to request updates from a custom server, NEXT button is disabled. Only UPDATE button is possible to be pressed.

And if I press UPDATE, it updates without checking version numbers at all. Meaning, I already have the latest firmware version flashed (same version that I have on the server) and when I click UPDATE, it downloads and flashes it again. Is this because version numbers of those new binaries aren't checked before flashing them and version checking is supported only from GitHub? If yes, it makes sense not to support auto updates from a custom server. To have this supported, I think I would need to have a separate json file in the folder that would have version information of the binaries.

![image](https://user-images.githubusercontent.com/1311912/131247001-bd02fe0b-f049-4e57-9153-39150b16656b.png)

**Comment by TheSomeMan** [comment]
> Is this because version numbers of those new binaries aren't checked before flashing them and version checking is supported only from GitHub?

yes, we can't get version number from binary files.
Latest release info is downloaded from https://api.github.com/repos/ruuvi/ruuvi.gateway_esp.c/releases/latest in json format.

> If yes, it makes sense not to support auto updates from a custom server.

yes, I don't see much point in users posting updates on their own server

**Comment by laurijamsa** [comment]
I have updated the strings a bit so that it'd be more clear what this does.
