### ISSUE TITLE
Popup window "Connection to the Ruuvi Gateway is lost" looks not good

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#114]
![image](https://user-images.githubusercontent.com/4346875/131350037-4e6dee76-87ed-4699-be53-e2a199504d1e.png)

**Comment by aj-ua** [comment]
Fixed popup styles.
Created PR https://github.com/ruuvi/ruuvi.gwui.html/pull/115
