### ISSUE TITLE
When LAN access is denied from everyone, UI is unclear

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gwui.html#143]
Instead of showing language selection, user should be prompted to press the configuration button if all LAN access is denied.
![image](https://user-images.githubusercontent.com/2360368/136801479-e2d55fa2-c363-4058-a998-3069f5cfc535.png)

**Comment by TheSomeMan** [comment]
![image](https://user-images.githubusercontent.com/4346875/139848080-5572b3a9-7edb-4ca1-9c48-f4928f3a2b14.png)

![image](https://user-images.githubusercontent.com/4346875/139848140-4f94d124-751c-4bf9-8c02-40440eadd485.png)

**Comment by ojousima** [comment]
Is it easy to remove the "choose language" dialog?

**Comment by markoaamunkajo** [comment]
QA passed
