### ISSUE TITLE
Add a clarification where the user can get the default password for accessing from LAN

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#159]
[link](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/435)

**Comment by TheSomeMan** [comment]
![image](https://user-images.githubusercontent.com/4346875/142142808-6b9f9975-4c08-47ef-ab94-3f59231941c3.png)

**Comment by TheSomeMan** [comment]
![image](https://user-images.githubusercontent.com/4346875/142142941-5709f30d-e0ec-4ce7-a122-40ef246cfd42.png)

**Comment by TheSomeMan** [comment]
@laurijamsa could you please check UI and translation?

**Comment by laurijamsa** [comment]
I thought that the remote configuration option would be on by default. Is it not? https://github.com/ruuvi/ruuvi.gwui.html/blob/9a43d02816f91cd4555a9fbf12bdfe22b3567956/src/index.html#L938-L939
https://github.com/ruuvi/ruuvi.gwui.html/blob/9a43d02816f91cd4555a9fbf12bdfe22b3567956/src/index.html#L923-L925

These lines need more info:
https://github.com/ruuvi/ruuvi.gwui.html/blob/9a43d02816f91cd4555a9fbf12bdfe22b3567956/src/index.html#L962-L963

On the bottom of the device we don't tell that the unique id (XX:XX:XX:XX:XX:XX:XX:XX) is a password. So we need to add more information here and also on the login page. Also, how the default password field shows only 8 "*" characters if default password is 48-bit id that has 16 hex characters + 7 semicolons? What's format of the password?

**Comment by TheSomeMan** [comment]
> Also, how the default password field shows only 8 "*" characters if default password is 48-bit id that has 16 hex characters + 7 semicolons? What's format of the password?

It's for security reasons. Passwords never transmitted to the browser, so it doesn't know the length of the password and if password is set, then it is always displayed as eight "*" regardless of its length. If an attacker knows the length of the password, it makes the bruteforcing task much easier.
Although the browser has information that the default password is used, so we can show hint "XX:XX:XX:XX:XX:XX:XX:XX" instead of "********".

**Comment by TheSomeMan** [comment]
![image](https://user-images.githubusercontent.com/4346875/142362183-62ac8861-df51-4be7-b18c-882a902b8bfb.png)

![image](https://user-images.githubusercontent.com/4346875/142362303-6f49c72a-d4a5-4a75-b3d2-a10d88516235.png)

@laurijamsa could you please check updated UI and translation?

**Comment by laurijamsa** [comment]
Translations are not perfect and the UI is currently a bit confusing because first it's told what the defaults are but to a new user it looks like that he should modify the defaults for some reason. And when doing it, I did run into another issue: https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/442

This settings view could be more clear if we'd have a fourth radio button:

* Use password protection with default password (default, safe)
* Use custom password protection (advanced, safe if using a strong password)
* No remote configuration access (safe)
* Allow remote configuration without password (unsafe, not recommended)

**Comment by TheSomeMan** [comment]
![image](https://user-images.githubusercontent.com/4346875/144048425-4abfcf65-d91a-4154-9595-b20b43ca3d0b.png)

![image](https://user-images.githubusercontent.com/4346875/144048524-4f609837-bc5d-400c-9b91-c1d3259db1bd.png)
