### ISSUE TITLE
Return view after disconnecting from WiFi

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gwui.html#17]
![image](https://user-images.githubusercontent.com/2360368/86612119-4faf5600-bfb8-11ea-9f31-978b82382c27.png)

returns to 
![image](https://user-images.githubusercontent.com/2360368/86612148-576efa80-bfb8-11ea-8b48-0745b16c2abf.png)

Expectation would be to return to 
![image](https://user-images.githubusercontent.com/2360368/86612159-5ccc4500-bfb8-11ea-83d6-b7413186e44a.png)

Reported by Henri.

**Comment by TheSomeMan** [comment]
I've tested it, it works as expected in the current version.
