### ISSUE TITLE
Enhance user experience when selecting where to send data

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gwui.html#174]
This issue doesn't contain a spec just yet, but this is a reminder that we need to discuss about this matter. Now it's not really easy to understand that can user send data to which targets simultaneously. We have received questions from users that can they send to Ruuvi Cloud + MQTT or Ruuvi Cloud + HTTP or Ruuvi Cloud + HTTP + MQTT and so on. 

We had an issue about this earlier but it was only partially implemented after a mutual discussion (that seems to be not documented in the issue):

https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/287

**Comment by ojousima** [comment]
Let's discuss this in https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/597

**Comment by markoaamunkajo** [comment]
Will be handled with https://github.com/ruuvi/ruuvi.gwui.html/issues/249
