### ISSUE TITLE
Time Synchronization Options is not easy to find

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gwui.html#192]
Description:

Checking the card https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/523  I had really hard time understanding how to get to this page. 

I think it should be more obvious, maybe show the Time Synchronization Options under the Custom Server page.

**Comment by ojousima** [comment]
Is this still valid as of `v1.12.1-36-g1091112` It's a part of Custom Server configuration flow and hard to miss

**Comment by laurijamsa** [comment]
This is easy to find now. Closing.
