### ISSUE TITLE
Fix typos and make some clarifications

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#193]
- "NTP-Server" -> "NTP Server"
- "HTTP-Server" -> "HTTP Server"
- synchronization -> synchronisation
- Custom Server: "Server Address" -> "Server Address (default: https://network.ruuvi.com/record)"
- Custom Server: HTTP -> HTTP(S), MQTT -> MQTT(S)
- Cloud options: "Use a custom server and configure more settings" -> "Use Ruuvi Cloud or/and a custom server and configure more settings"

**Comment by laurijamsa** [comment]
Finnish: "Käytä Ruuvi Cloudia ja/tai muuta palvelinta sekä säädä muita lisäasetuksia"

**Comment by TheSomeMan** [comment]
This task is a subtask of [this one](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/535)

**Comment by markoaamunkajo** [comment]
Qa passed
