### ISSUE TITLE
Internet Connection: By default, the connection type should be Ethernet

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#196]

**Comment by TheSomeMan** [comment]
This task is a subtask of [this one](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/535)

**Comment by TheSomeMan** [comment]
Moved to the main project [link](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/536)

**Comment by markoaamunkajo** [comment]
QA passed
