### ISSUE TITLE
WiFi Network: Usability improvements

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#197]
- WiFi: disable checkbox "Show Password" if the saved password is used, enable this checkbox only after manually entering a password
- WiFi: Increase padding after "Show Password"
- WiFi: when a row with WiFi name is selected, then the cursor should not change its shape as if it were over the link

**Comment by TheSomeMan** [comment]
This task is a subtask of [this one](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/535)

**Comment by markoaamunkajo** [comment]
QA passed
