### ISSUE TITLE
UI sometimes gets stuck on "WiFi network" page when error occurs on ap.json request  

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#199]

**Comment by markoaamunkajo** [comment]
@TheSomeMan I was able to reproduce this by first making full reset for gw, then choosing ethernet settings with no cable attached and then returning back and choosing wifi.

https://user-images.githubusercontent.com/50437378/179996563-d9520ca8-be03-4ef8-8a7b-a61614cc737e.mov

**Comment by ojousima** [comment]
Moving this to review by @markoaamunkajo

**Comment by markoaamunkajo** [comment]
Hi retested this with build 667 from Jenkins. Same result.
Steps:

Updated firmware, made full reset using hw pin on gateway, opened configurator using wifi hotspot, configured ethernet without cable connected, waited for timeout, went back and chose wifi, opened wifi list is empty even after extended period.

Please find logs attached.

<img width="898" alt="Screenshot 2022-07-29 at 14 38 31" src="https://user-images.githubusercontent.com/50437378/181709186-2447f28d-3462-4fb2-a851-c0b1df65027a.png">

[no_wifi_listed.txt](https://github.com/ruuvi/ruuvi.gwui.html/files/9217629/no_wifi_listed.txt)

**Comment by markoaamunkajo** [comment]
QA passed
