### ISSUE TITLE
Software update: add an icon for advanced settings, which can call a pop-up window with additional information

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#203]
It is necessary to describe which binaries are required to install the update.

**Comment by laurijamsa** [comment]
I think the discussed information toast messages are a bit big task to be implemented in 1.12 so maybe this task could be just to enhance the descriptions by telling the user to find more information on docs.ruuvi.com

**Comment by ojousima** [comment]
I marked this now as v1.12.2, but we can move it to v1.13.0 if this is a big task

**Comment by markoaamunkajo** [comment]
QA passed
