### ISSUE TITLE
Password is bold for a moment and after bolding is removed, it still looks semi bold

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gwui.html#240]
https://user-images.githubusercontent.com/1311912/191571380-ede66076-0db6-440b-85c2-16c9a5f040a9.mov

**Comment by TheSomeMan** [comment]
It seems that this problem only affects Mac/iPhone users.
It looks like Safari renders the 'font-weight: 600' style (semi-bold) with some delay. 
At the first stage, it applies the default bold style (font-weight=700), then after a delay, it applies the actual font-weight=600.
In both cases, if standard or bold 'font-weight' is used, the problem does not appear.
@laurijamsa should we replace 'semi-bold' style to 'bold' for the 'Password' title?

**Comment by laurijamsa** [comment]
Actually, we can just remove the whole "Password" title I think as we already have a similar Password placeholder on the input field.

**Comment by TheSomeMan** [comment]
That's not true, the 'Password' placeholder was removed and the placeholder now is used to show '********' when a saved password is used:
![image](https://user-images.githubusercontent.com/4346875/201914451-11b80996-32a9-4a5f-a2f1-82462a2018d2.png)

Also, the same 'Password' field is used for manual connection:
![image](https://user-images.githubusercontent.com/4346875/201914848-7148fa16-ed67-4de9-90e9-79437623df8f.png)

**Comment by markoaamunkajo** [comment]
QA passed
