### ISSUE TITLE
Static Ethernet IP address fails unless all fields are given

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#245]
[link](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/544)

**Comment by TheSomeMan** [comment]
![image](https://user-images.githubusercontent.com/4346875/196605599-9399cf84-944c-4ca6-b485-81b04cb5ee65.png)

**Comment by markoaamunkajo** [comment]
QA passed
