### ISSUE TITLE
Add "Configure" button to continue configuring the gateway after nRF52 firmware update fails

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#257]
[link](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/660)

**Comment by markoaamunkajo** [comment]
Reset nRF during flashing

**Comment by markoaamunkajo** [comment]
I can not get to Configure in any tests I tried with given instructions.

**Comment by TheSomeMan** [comment]
It's quite tricky to simulate the conditions for the "Configure" button to appear.
If you simulate SWD hardware problem during the last stage of firmware updating, then the gateway will be rebooted and nRF52 flashing continues. If after reboot the gateway can't read nRF52 firmware version, then it will try to rollback firmware and reboot or if rollback is not possible, then it will not start nRF52 firmware updating.

So, we need to reboot the gateway during the last stage of firmware updating, then wait until nRF52 firmware flashing is started, then simulate SWD error. But if firmware rollback is possible, then the gateway will be rolled back and restarted (you can see "Configure" button in this case, but only for 5 seconds until the gateway reboot).

Therefore, to simulate the conditions, we need to have a previous firmware version on the gateway of at least 1.13.x and the current version 1.13.x (and nRF52 firmware in these versions must be different). If these conditions are met, the gateway will rollback firmware, then try to flash nRF52 again and if SDW error occurs again, then the gateway will start WiFi AP and display an error message and "Configure" button.

The problem now is that we have only v1.13.0 with nRF52 firmware v1.0.0, so we can't simulate switching nRF52 firmware using different gateway versions. 
But there is a workaround to prevent firmware rollback:
1. Flash v1.12.4 with esptool
2. Flash v1.13.0 with esptool
3. Wait until nRF52 flashing is started
4. Connect to WiFi AP
5. Simulate SWD error
6. Check that "Configure" button is displayed:
![image](https://user-images.githubusercontent.com/4346875/218320405-e1281e27-21ca-4445-8953-c458f8dd6eb5.png)

7. WiFi AP will be turned off after 5 seconds
8. If the gateway was configured to allow access via LAN, then you can connect to it and see the error message "Failed to update nRF52 firmware" and the "Configure" button. Notice, that if default LAN authentication is used, the password "FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF:FF" must be used, as we could not read the device ID from nRF52.
![image](https://user-images.githubusercontent.com/4346875/218320442-1a1b4b47-2219-4f92-9d0d-8bb982a7cad2.png)

**Comment by markoaamunkajo** [comment]
Finally! This issue is QA passed.
