### ISSUE TITLE
Sort wifi networks in alphabetical order

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#259]
[link](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/672)

**Comment by laurijamsa** [comment]
What will happen if my network is named ZZZ and there are 30 or more other networks nearby? Someone just said on the Ruuvi telegram channel that once there were 1800 other Wi-Fi networks available when he tried to configure some other device and it froze completely. This should not happen to Ruuvi Gateway and it should be also always possible to select my ZZZ network even if there were number of other networks in range. In these situations, can user currently use the manual SSID selection?

**Comment by markoaamunkajo** [comment]
QA passed
