### ISSUE TITLE
Configuration screen says RESET button Should be the button stenciled CONFIGURE

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.gwui.html#28]
ALL GOOD!
...
"RESET button on bottom of the Gateway."
There is no button labeled reset, do you mean **Reboot**

**Comment by ojousima** [comment]
Are you referring to something in UI? What exactly?

**Comment by DG12** [comment]
The last screen in the configuration setup.
index.html line 564
section id="thankyou"

**Comment by ojousima** [comment]
This one? Thanks for running the simulator on a public server btw. 
<img width="653" alt="image" src="https://user-images.githubusercontent.com/2360368/89180861-49060580-d59b-11ea-8222-9ee36981cf27.png">

The correct wording would be `If you want to modify the settings, press and hold CONFIGURE button on bottom of the Gateway for at least five seconds.`

@TheSomeMan ^

**Comment by DG12** [comment]
Revised title

**Comment by TheSomeMan** [comment]
@ojousima , what is the correct translation of this phrase in Finnish? "If you want to modify the settings, press and hold CONFIGURE button on bottom of the Gateway for at least five seconds."

**Comment by ojousima** [comment]
@TheSomeMan "Jos haluat muokata asetuksia, paina ja pidä pohjassa vähintään viisi sekuntia CONFIGURE-näppäintä gatewayn takapuolella"

**Comment by DG12** [comment]
Thanks
