### ISSUE TITLE
Mobile layout: styling fixes

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#283]
[link](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/718)

**Comment by markoaamunkajo** [comment]
Main card moved back, this one done.

**Comment by markoaamunkajo** [comment]
This needs to be realigned to fit on page

![Image](https://user-images.githubusercontent.com/50437378/235409719-2dcc8bfa-8862-4694-a562-ec3e6e56f2ee.jpg)

**Comment by markoaamunkajo** [comment]
Still not fitting properly

![Image](https://user-images.githubusercontent.com/50437378/235813668-6195e2d1-7386-461e-8bcd-c55d87dce7c3.jpeg)

**Comment by markoaamunkajo** [comment]
These two should be fixed.

We can use the vertical line ｜ at the bottom version info divider, the font size should be same size as text.

![Image](https://github.com/ruuvi/ruuvi.gwui.html/assets/50437378/b7164a4a-c236-4449-8b94-0687aa504944)
![Image](https://github.com/ruuvi/ruuvi.gwui.html/assets/50437378/f3c2df16-7023-4b63-9c21-e8853fcca594)

**Comment by markoaamunkajo** [comment]
QA passed
