### ISSUE TITLE
Attempt to connect for initial configiuration using macBook fails

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.gwui.html#29]
Selecting **Ruuvigateway mmmm** with
Catalina 10.15.6 

captive network assistant fails and reports

A problem occured
The webpage couldn't be loaded

**Comment by ojousima** [comment]
I can try to replicate on my end. Which exact firmware you're running on gateway?

**Comment by DG12** [comment]
Factory installed as of 7/30/20. As there is no version on the wizard screen how can I tell?

**Comment by DG12** [comment]
Does this issue belong to esp32-wifi-manager ? see additional details there
https://github.com/ruuvi/esp32-wifi-manager/issues/25
