### ISSUE TITLE
Make it possible to whitelist MAC addresses on the Gateway web UI

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#292]
[Link to issue 238](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/238)

**Comment by sini-maaria** [comment]
Check the paddings on the current ui. 

Current is on the left side and my example on the right side of the image.

![paddings](https://github.com/ruuvi/ruuvi.gwui.html/assets/19531763/fe48cfb5-dd7b-468b-974a-2c8d20c0129e)

**Comment by markoaamunkajo** [comment]
@TheSomeMan layout fixes

**Comment by TheSomeMan** [comment]
Test build: https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/934/artifact/build/

**Comment by markoaamunkajo** [comment]
@TheSomeMan I made one string change to gwui index file, I think that it needs to be merged

https://github.com/ruuvi/ruuvi.gwui.html/pull/299/commits

**Comment by TheSomeMan** [comment]
> @TheSomeMan I made one string change to gwui index file, I think that it needs to be merged
> 
> https://github.com/ruuvi/ruuvi.gwui.html/pull/299/commits

Since you committed your changes on the same branch, there is no need to merge it. I included your changes to my PR.

**Comment by markoaamunkajo** [comment]
QA passed
