### ISSUE TITLE
Update Finnish translations

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gwui.html#30]
Some things, such as "IP Address" are not translated and some strings are Google Translated. A native speaker needs to take a look at the translation.

**Comment by ojousima** [comment]
@markoaamunkajo will do the translation, let's look how to integrate Translations to UI once translations are ready

**Comment by laurijamsa** [comment]
Better to modify directly the index.html file... Or is there a reason not to do so?

**Comment by ojousima** [comment]
> Better to modify directly the index.html file... Or is there a reason not to do so? 

Some of the strings do not have an immediately obvious way of entering them

**Comment by TheSomeMan** [comment]
[Add Finnish translations / update existing](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/151)
