### ISSUE TITLE
Support user SSL certs

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#300]
[Link to issue 476](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/476)

**Comment by markoaamunkajo** [comment]
Check UI with Lauri

**Comment by markoaamunkajo** [comment]
#915 build

**Comment by markoaamunkajo** [comment]
Looks like SSL is not under authentication methods but as a separate section in this build. We will discuss with Otso and make decision.

**Comment by TheSomeMan** [comment]
> Looks like SSL is not under authentication methods but as a separate section in this build. We will discuss with Otso and make decision.

SSL cert is independent of authentication. You can use SSL cert only, but don't use authentication.
