### ISSUE TITLE
Don't use FadeIn/FadeOut for an advanced section when a page is opened

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#311]

**Comment by markoaamunkajo** [comment]
@TheSomeMan these fades still existing in build 957, maybe not merged?

**Comment by TheSomeMan** [comment]
> @TheSomeMan these fades still existing in build 957, maybe not merged?

What page?

**Comment by markoaamunkajo** [comment]
For example 

All advanced tabs
Statistics



https://github.com/ruuvi/ruuvi.gwui.html/assets/50437378/033579a1-2c48-45c3-a208-c02b733994e7

**Comment by TheSomeMan** [comment]
But it's correct behavior. Fade in/out should be used when the user manually opens/closes Advanced settings.
The problem was that if non-default settings are used and Advanced section is to be displayed automatically when the page is opened, it is not needed to do this smoothly using FadeIn.

**Comment by markoaamunkajo** [comment]
@laurijamsa I remember this case was to remove all fades from advanced/opened or closed tabs. Am I correct?

**Comment by laurijamsa** [comment]
Maybe we have also discussed at some point to remove all fadings but after watching your video, I assume that it is not actually necessary if they don't cause us any problems.

**Comment by markoaamunkajo** [comment]
Ok let's move this to done, I consider there is no changes needed here.
