### ISSUE TITLE
Add support for configuring the scanning options

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#34]
use_coded_phy
use_1mbit_phy
use_extended_payload
use_channel_37
use_channel_38
use_channel_39

**Comment by ojousima** [comment]
As a quick note, default could be
```
use_coded_phy = 0,
use_1mbit_phy = 1,
use_extended_payload  = 1,
use_channel_37  = 1,
use_channel_38 = 1,
use_channel_39 = 1
```

**Comment by ojousima** [comment]
Another note, currently ESP32 sends "0" on all fields to nRF52 which *should* mean that nRF52 doesn't scan anything at all but due to a bug in nRF52 0.5.1 FW nRF52 ends up scanning on Coded PHY only, which looks like not scanning at all unless some devices nearby happen to be using Coded PHY.

**Comment by TheSomeMan** [comment]
@ojousima please check my initial implementation of the scanning options:
![image](https://user-images.githubusercontent.com/4346875/112377379-3e5dd380-8d18-11eb-86d6-ace5976f59fb.png)
All these settings should be displayed only when filtering is disabled, right?
And could you translate these phrases into Finnish?

**Comment by ojousima** [comment]
Let's add a choice for "Include experimental BLE 5.0 long range sensors" for Coded PHY under "Ruuvi Sensors only".

"Which devices to scan" -> "Valitse skannattavat laitteet"
"Ruuvi sensors only" -> "Vain Ruuvin anturit"
"All nearby Bluetooth beacons (for advanced users)" -> "Kaikki lähistön Bluetooth-majakat (edistyneille käyttäjille)"
"Use Coded PHY" -> "Skannaa virheenkorjattuja lähetyksiä"
"Use 1 MBit PHY" -> "Skannaa 1 MBit lähetyksiä"
"Use extended payload" -> "Skannaa pidennettyjä lähetyksiä"
"Use channel XX" -> "Skannaa kanavaa XX"

**Comment by TheSomeMan** [comment]
@ojousima what is the Finnish translation of the phrase "Include experimental BLE 5.0 long range sensors" for Coded PHY under "Ruuvi Sensors only"?

**Comment by ojousima** [comment]
"Include experimental BLE 5.0 long range sensors" -> "Skannaa myös kokeellisia BLE 5.0 pitkän kantomatkan antureita"

**Comment by TheSomeMan** [comment]
![image](https://user-images.githubusercontent.com/4346875/113030776-2377dd00-91b8-11eb-89cf-4ba22505c9f4.png)

![image](https://user-images.githubusercontent.com/4346875/113030841-38547080-91b8-11eb-825e-112c899ff413.png)

**Comment by ojousima** [comment]
Looks good to me
