### ISSUE TITLE
prevent web browser from remembering API keys

### ISSUE THREAD

**Issue by jheba** [ruuvi/ruuvi.gwui.html#388]
Hello,

Please consider to use input type `password` instead of `text` for API key fields, to prevent web browsers from remembering them as they are sensitive information.
![image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/290289/0b8af9b1-04eb-48ca-8bba-f30af1142187)

![image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/290289/361cd8b2-a4ee-4985-9f5b-7436d390cd51)

**Comment by ojousima** [comment]
Thanks, good catch. Let's check the other password fields while we're at it.

**Comment by markoaamunkajo** [comment]
QA passed
