### ISSUE TITLE
After connecting to a WiFi network successfully, it's not clear for the user that the configuration is now completed

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gwui.html#59]
[link](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/84)

**Comment by TheSomeMan** [comment]
![image](https://user-images.githubusercontent.com/4346875/113093941-0de7cf00-921b-11eb-9ef3-af73dd5307ba.png)

**Comment by TheSomeMan** [comment]
@ojousima could you please translate into Finnish following phrases:
* "You can now close this window"
* "If you want to start WiFi AP and change settings, press and release the CONFIGURE button on the bottom of the Gateway,          then connect to the WiFi access point."
* "If you want to reset settings and configure the Gateway from scratch, disconnect the Ethernet cable from the Gateway,                         press and hold the CONFIGURE button on the bottom of the Gateway for at least five seconds, then connect to the WiFi access point."
* "TCP/IP settings:"

**Comment by ojousima** [comment]
"You can now close this window" -> "Voit nyt sulkea tämän ikkunan"

"If you want to start WiFi AP and change settings, press and release the CONFIGURE button on the bottom of the Gateway, then connect to the WiFi access point." -> "Jos  haluat käynnistää WiFi-tukiaseman muokataksesi asetuksia, paina lyhyesti näppäintä USB-virtaliittimen päällä ja yhdistä Gatewayn WiFi-verkkoon" 

__note__ English version should also be updated, "If you want to start WiFi AP and change settings, press and release the button on top of the USB-power connector, then connect to the WiFi access point of the Gateway."

"If you want to reset settings and configure the Gateway from scratch, disconnect the Ethernet cable from the Gateway, press and hold the CONFIGURE button on the bottom of the Gateway for at least five seconds, then connect to the WiFi access point." -> "Jos haluat nollata asetukset ja uudelleenkonfiguroida Gatewayn, irroita Ethernet-kaapeli Gatewaystä, paina ja pidä pohjassa Gatewayn USB-virtaliittimen päällä olevaa näppäintä ainakin viisi sekuntia ja yhdistä sitten Gatewayn WiFi-verkkoon."

"TCP/IP settings:" -> "TCP/IP asetukset:"
