### ISSUE TITLE
GW OTA update fail can result user to get stuck in configurator

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gwui.html#85]
Description:

User has firmware 1.4 and is in web configurator to setup his new gateway. He is suggested to update firmware from 1.4->1.7 and user chooses to do so. However the update fails and user needs to start the configurator again from first page.

Actual: user is always redirected from first page to failed firmware update page, there is no way out for user.
Expected: allow user to restart process without rebooting device.

**Comment by markoaamunkajo** [comment]
https://user-images.githubusercontent.com/50437378/129594667-dd53e00b-6b13-4182-ab9b-8b93aea8b65a.mov

**Comment by ojousima** [comment]
1.4 OTA update is buggy, this is fixed in 1.6. 1.4 Users must flash by USB.

Nothing more can be done, closing
